### ISSUE TITLE
DriverWrapper invoking the app two times. 

### ISSUE THREAD

**Issue by anim2k19** [healenium/healenium-appium#51]
### Describe the problem

My app is invoking two times after using wrap function like this in beforeTest: -

```
@BeforeTest(alwaysRun = true)
	public void beforeTest() throws IOException {
		driver = getDriver("emulator-5554", "Android", "11") ;
		driver = DriverWrapper.wrap(driver);
		signIn = new SignInHelper(driver);
	}
```
getDriver function :-
```
public static AppiumDriver<MobileElement> getDriver(String deviceName, String platformName,
			String platformVersion) {
		try {
			if (runOnBrowserStack) {
				setBrowserStackAndroidCapabilities(deviceName, platformName, platformVersion);
				driver = new AppiumDriver<MobileElement>(new URL("https://" + browserStackUserName + ":"
						+ browserStackAccessKey + "@hub-cloud.browserstack.com/wd/hub"), cap);
				driver.manage().deleteAllCookies();
				driver.manage().timeouts().implicitlyWait(Time.TIME_OUT_IN_SECONDS, TimeUnit.SECONDS);
			} else {
				setLocalAndroidCapabilities(deviceName, platformName, platformVersion);
				driver = new AppiumDriver<MobileElement>(service.getUrl(), cap);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return driver;
	}
```
SignInHelper :- 
```
public class SignInHelper extends BaseClass {
	private AppiumDriver<MobileElement> driver;

	public SignInHelper(AppiumDriver<MobileElement> driver) {
		this.driver = driver;
		PageFactory.initElements(new AppiumFieldDecorator(driver), this);
	}
}
```
### Healenium Backend version

3.2.2

### Healenium Appium version

1.18.0

### Logs appeared during using Healenium

```shell
Jun 22, 2022 5:13:32 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Jun 22, 2022 5:13:42 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
```

**Comment by neofreko** [comment]
CMIIW, this is caused by a proxy class healenium use to wrap the driver. [Instantiating the proxy](https://github.com/healenium/healenium-appium/blob/fe07580156d633ffac6f7dd44c69f78c34f6701f/src/main/java/com/epam/healenium/appium/wrapper/DriverWrapper.java#L72) means instantiating another Appium driver which of course create another session. Unfortunately, Appium Java client cannot attach itself to existing session. There's two options here:
1. Re-work the wrapper. But this goes all the way to healenium.
2. Add "[attach to existing session](https://github.com/appium/java-client/pull/1181)" to Appium Java client.

**Comment by Alex-Reif** [comment]
Hi @anim2k19 , @neofreko , issue was fixed at rev. 1.4.0
